---
env:
  node: true
  es6: true
  mocha: true
parserOptions:
  emcaVersion: 6
  sourceType: module
plugins:
  - mocha
root: true
rules:
  array-bracket-spacing: [1, never]
  block-spacing: [1, never]
  brace-style: [1, stroustrup]
  camelcase: 1
  comma-dangle: [1, always-multiline]
  constructor-super: 1
  curly: 1
  eol-last: 1
  eqeqeq: 1
  indent: [1, 2]
  key-spacing: 1
  keyword-spacing: 1
  linebreak-style: [1, unix]
  lines-around-comment:
    - 1
    - allowArrayStart: true
      allowBlockStart: true
      allowObjectStart: true
      beforeBlockComment: true
      beforeLineComment: true
  max-len: [1, 79]
  newline-before-return: 1
  no-bitwise: 1
  no-cond-assign: 1
  no-confusing-arrow: 1
  no-const-assign: 1
  no-dupe-class-members: 1
  no-implicit-coercion: 1
  no-plusplus: 1
  no-shadow: 1
  no-shadow-restricted-names: 1
  no-ternary: 1
  no-this-before-super: 1
  no-undef: 1
  no-unused-vars: 1
  no-whitespace-before-property: 1
  object-curly-spacing: [1, never]
  one-var: [1, never]
  padded-blocks: [1, never]
  quote-props:
    - 1
    - consistent-as-needed
    - keywords: true
  quotes: [1, single, avoid-escape]
  require-jsdoc:
    - 1
    - require:
        ClassDeclaration: true
        FunctionDeclaration: true
        MethodDefinition: true
  semi: [1, always]
  space-before-blocks: 1
  space-in-parens: 1
  space-infix-ops: 1
  spaced-comment: 1
  strict: 1
  template-curly-spacing: 1
  wrap-iife: [1, inside]
  yoda: [1, never]
